# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "Frontdown"
license = "MIT"
licenselink = "https://github.com/Frontdown24/fd-theme/blob/main/LICENSE"
description = "Frontdown is the perfect solution for managing your backups."
homepage = "https://github.com/Frontdown24/fd-theme"
demosite = "https://demo.frontdown.me/"
tags = ["Backup", "Management", "Easy", "Cloud", "Secure", "Reliable", "Automation"]
features = ["Easy Setup", "Secure Storage", "Cloud Integration", "Automated Backups", "Customizable", "Scheduling", "Backup History", "Multi-platform Support"]
min_version = "0.130.0"

[author]
  name = "Frontdown"
  homepage = "https://frontdown.me/"
